' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../fta_metamodel.puml

$TopEvent("StartFindService callback is called unexpectedly", "TopEvent")

$OrGate("Gate1", "TopEvent")
$BasicEvent("Called reduandently", "Event2", "Gate1")
$BasicEvent("Called eventhough StopFindService has been called", "Event3", "Gate1")
$IntermediateEvent("Called wrongly", "Event1", "Gate1")
$OrGate("Gate2", "Event1")
$BasicEvent("Watches are set wrongly", "Event5", "Gate2")
$BasicEvent("Inotify returns wrong information", "Event4", "Gate2")

@enduml
