# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "call_method_fta",
    srcs = [
        "call_blocks_fta.puml",
        "wrong_in_args_provided_fta.puml",
        "wrong_results_used_fta.puml",
    ],
    visibility = ["//visibility:public"],
)
