' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../fta_metamodel.puml

$TopEvent("Callback not invoked, despite samples available", "Communication.CallbackNotInvokedDespiteSamplesAvailable")

$OrGate("Gate1", "TopEvent")
$IntermediateEvent("Search Logic is broken", "Event1", "Gate1")
$OrGate("Gate2", "Event1")
$IntermediateEvent("Wrong slot status / timestamp is set", "Event4", "Gate2")
$OrGate("Gate3", "Event4")
$BasicEvent("Wrong value inserted", "Communication.WrongValueInserted", "Gate3")
$IntermediateEvent("Unintended Memory overwrite", "Event7", "Gate3")
$IntermediateEvent("QM process writes into ASIL segment", "Event8", "Event7")
$BasicEvent("Wrong ACL configuration for SHM segments", "Communication.WrongAclConfigurationForShmSegments", "Event8")
$IntermediateEvent("Local Time-Stamp in Proxy event instance is corrupted", "Event3", "Gate2")
$BasicEvent("Wrong value inserted", "Communication.WrongValueInserted", "Event3")
$BasicEvent("Callback is not stored correctly", "Communication.CallbackIsNotStoredCorrectly", "Gate1")

@enduml
