' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../fta_metamodel.puml

$TopEvent("No resources freed", "Communication.NoResourcesFreed")

$IntermediateEvent("No Unlink / unmap shm-region", "Event1", "TopEvent")
$OrGate("Gate1", "Event1")
$BasicEvent("No unmap on destruction", "Communication.NoUnmapOnDestruction", "Gate1")
$BasicEvent("Shared Memory segment is not unlinked", "Communication.SharedMemorySegmentIsNotUnlinked", "Gate1")

@enduml
