' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../fta_metamodel.puml

$TopEvent("Wrong resources freed", "TopEvent")

$IntermediateEvent("Unlink / unmap shm-region of different instance", "Event1", "TopEvent")
$OrGate("Gate1", "Event1")
$IntermediateEvent("Shared Memory Ressource associates wrong shared memory segment", "Event2", "Gate1")
$BasicEvent("Wrong name of shared memory segment", "Event4", "Event2")
$IntermediateEvent("Shared Memory Resource holds wrong base pointer", "Event3", "Gate1")
$BasicEvent("Wrong memory resource proxy", "Event5", "Event3")

@enduml
