# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "the_size_returned_is_bigger_then_the_actual_value_fta",
    srcs = [
        "the_size_returned_is_bigger_then_actual_value_fta.puml",
    ],
    visibility = ["//visibility:public"],
)
