# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "smart_pointer_fta",
    srcs = [
        "//score/mw/com/dependability/requirements/safety_analysis/root_causes/smart_pointer/method_signature_element_ptr:method_signature_element_ptr_fta",
        "//score/mw/com/dependability/requirements/safety_analysis/root_causes/smart_pointer/sample_ptr_sample_allocate_ptr",
    ],
    visibility = ["//visibility:public"],
)
