test_suite(
    name = "component_tests",
    tests = [
        "//score/mw/com/test/methods/basic_acceptance_test:component_tests",
        "//score/mw/com/test/methods/signature_variations:component_tests",
    ],
    visibility = ["//score/mw/com/test:__pkg__"],
)
