@startuml get_owner_uid_seq

participant SharedMemoryResource
participant "os::Stat" as os
participant TypedMemory
participant "typed_memory_daemon" as tmd

[->  SharedMemoryResource: GetOwnerUid(fd)
SharedMemoryResource -> os : fstat(fd)
os -> SharedMemoryResource: return StatBuffer

SharedMemoryResource -> SharedMemoryResource: set owner_uid = StatBuffer.uid

alt StatBuffer.uid == typed memory manager uid && memory is named
    SharedMemoryResource -> TypedMemory: GetCreatorUid(shm_name)
    TypedMemory -> tmd: query ownership map
    tmd -> TypedMemory: return creator_uid

    alt creator_uid retrieval failed
        note over SharedMemoryResource
        Unable to retrieve creator UID from
        typed_memory_daemon ownership map
        Process is terminated
        endnote
        SharedMemoryResource -> SharedMemoryResource: std::terminate()
        destroy SharedMemoryResource
    end

    TypedMemory -> SharedMemoryResource: return creator_uid
    SharedMemoryResource -> SharedMemoryResource: owner_uid = creator_uid
end

SharedMemoryResource ->[: return owner_uid

@enduml
