# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "root_causes_skeleton",
    srcs = [
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/allocate_an_event_or_field:allocate_in_wrong_memory_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/allocate_an_event_or_field:to_few_memory_allocated_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/creation:creation_of_skeleton_not_possible_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/destruction:no_resources_freed_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/destruction:wrong_resources_freed_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/offer_a_service:offers_already_offered_service_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/offer_a_service:only_partially_offered_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/offer_a_service:service_offered_under_wrong_id_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/offer_a_service:skeleton_not_offered_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/offer_a_service:skeleton_not_offered_without_initial_field_value_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/offer_a_service:skeleton_offered_wrong_binding_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/send_an_event_or_field:changes_user_data_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/send_an_event_or_field:does_not_free_resources_after_usage_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/send_an_event_or_field:only_partially_notifies_user_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/send_an_event_or_field:sends_to_wrong_consumer_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/stop_offer_a_service:only_partially_stop_offer_fta",
        "//score/mw/com/requirements/safety_analysis/root_causes/skeleton/stop_offer_a_service:stop_offer_on_wrong_ids_fta",
    ],
    visibility = ["//visibility:public"],
)
