# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""Shared logic for extracting public targets via bazel query."""

import os
import pwd
import subprocess

EXCLUDED_PUBLIC_TARGETS = {
    # Generated by @score_tooling dependable_element with hardcoded
    # visibility=["//visibility:public"] in external macro code.
    "//third_party/score_baselibs:bitmanipulation_rst",
    "//third_party/score_baselibs:containers_rst",
    "//third_party/score_baselibs:futurecpp_rst",
    "//third_party/score_baselibs:os_rst",
}


def get_all_public_targets(repo_root):
    """Get sorted list of all public targets in the repository using bazel query.

    This includes both explicitly declared and macro-generated targets.
    """
    cmd = [
        "bazel",
        "query",
        "attr(visibility, //visibility:public, //...)",
        "--output=label",
        "--keep_going",
        # The dependency-compatibility checker rewrites MODULE.bazel to pin
        # alternative versions, which makes the committed lockfile stale. Skip
        # lockfile verification so this nested query still resolves; on an
        # unmodified tree the lockfile matches and the result is unchanged.
        "--lockfile_mode=off",
    ]

    env = os.environ.copy()

    # When running inside `bazel test`, the outer Bazel client holds the server
    # lock, so a nested `bazel query` would block indefinitely.  Use a separate
    # output_base (and therefore a separate server) to avoid the deadlock.
    test_tmpdir = env.get("TEST_TMPDIR")
    if test_tmpdir:
        output_base = os.path.join(test_tmpdir, "bazel_query_output_base")
        cmd = ["bazel", f"--output_base={output_base}"] + cmd[1:]

        # `bazel test` strips HOME from the environment. When the `bazel`
        # binary is actually bazelisk, it needs HOME to locate the cached
        # Bazel download. Read it from the password database instead.
        if not env.get("HOME"):
            env["HOME"] = pwd.getpwuid(os.getuid()).pw_dir

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=repo_root,
        env=env,
        check=False,
    )
    targets = sorted(
        line.strip()
        for line in result.stdout.splitlines()
        if line.strip() and line.strip() not in EXCLUDED_PUBLIC_TARGETS
    )
    return targets
