# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
"""Shared logic for extracting public targets via bazel query."""

import os
import pwd
import re
import subprocess

EXCLUDED_PUBLIC_TARGETS = {
    # Generated by @score_tooling dependable_element with hardcoded
    # visibility=["//visibility:public"] in external macro code.
    "//third_party/score_baselibs:bitmanipulation_rst",
    "//third_party/score_baselibs:containers_rst",
    "//third_party/score_baselibs:futurecpp_rst",
    "//third_party/score_baselibs:os_rst",
}

# Matches the visibility() load-visibility built-in in .bzl files. Bazel
# accepts both a list argument (e.g. visibility(["//foo", "public"])) and a
# single string argument (e.g. visibility("//...")), so capture either form.
_BZL_VISIBILITY_CALL_RE = re.compile(r"\bvisibility\s*\(\s*(?P<items>\[.*?\]|['\"].*?['\"])\s*\)", re.DOTALL)

# Matches public entries inside the visibility() argument in .bzl files.
_BZL_PUBLIC_VISIBILITY_ITEM_RE = re.compile(r'["\'](?:public|//visibility:public)["\']')

# Directories (relative to repo root) that should never be scanned for .bzl files.
_SKIP_DIRS = {".git", "bazel-bin", "bazel-out", "bazel-testlogs"}


def _get_public_load_visibility_targets(repo_root):
    """Return labels for .bzl files that are publicly loadable.

    Bazel's load visibility (set via the visibility() built-in inside a .bzl
    file) controls which packages may load() the file.  Unlike target
    visibility, it is not exposed through bazel query's attr() predicate, so
    we detect it by scanning .bzl files directly.

    A .bzl file is considered public if:
    - It has no visibility(...) declaration (Bazel default is public), or
    - It explicitly declares public visibility, i.e. visibility("public"),
      visibility(["public"]) (or the "//visibility:public" spelling).

    Any other declaration (e.g. visibility("//...") which restricts loading to
    the main repository) is treated as non-public.
    """
    public_bzl_targets = []
    for dirpath, dirnames, filenames in os.walk(repo_root):
        rel_dir = os.path.relpath(dirpath, repo_root)
        # Skip Bazel-managed symlink trees, hidden directories, and any
        # directory that is itself a symlink.
        dirnames[:] = [
            d
            for d in dirnames
            if d not in _SKIP_DIRS and not d.startswith(".") and not os.path.islink(os.path.join(dirpath, d))
        ]

        for filename in filenames:
            if not filename.endswith(".bzl"):
                continue
            filepath = os.path.join(dirpath, filename)
            try:
                with open(filepath, encoding="utf-8", errors="replace") as fh:
                    content = fh.read()
            except OSError:
                continue

            # Strip comment lines before matching to avoid false positives.
            non_comment_content = "\n".join(line for line in content.splitlines() if not line.lstrip().startswith("#"))
            visibility_match = _BZL_VISIBILITY_CALL_RE.search(non_comment_content)
            if visibility_match:
                visibility_items = visibility_match.group("items")
                if not _BZL_PUBLIC_VISIBILITY_ITEM_RE.search(visibility_items):
                    continue

            # Convert filesystem path to a canonical Bazel label.
            if rel_dir == ".":
                label = f"//:{filename}"
            else:
                # Normalise path separators on all platforms.
                pkg = rel_dir.replace(os.sep, "/")
                label = f"//{pkg}:{filename}"

            if label not in EXCLUDED_PUBLIC_TARGETS:
                public_bzl_targets.append(label)

    return public_bzl_targets


def get_all_public_targets(repo_root):
    """Get sorted list of all public targets in the repository.

    Combines two sources:
    - BUILD rule/file targets with ``visibility = ["//visibility:public"]``
      (found via bazel query).
    - ``.bzl`` files that are publicly loadable (explicitly public visibility
      or no ``visibility([...])`` declaration, since Bazel's default is
      public). These are found by scanning source files directly, because bazel
      query's ``attr()`` predicate does not cover load visibility.
    """
    cmd = [
        "bazel",
        "query",
        "attr(visibility, //visibility:public, //...)",
        "--output=label",
        "--keep_going",
        # The dependency-compatibility checker rewrites MODULE.bazel to pin
        # alternative versions, which makes the committed lockfile stale. Skip
        # lockfile verification so this nested query still resolves; on an
        # unmodified tree the lockfile matches and the result is unchanged.
        "--lockfile_mode=off",
    ]

    env = os.environ.copy()

    # When running inside `bazel test`, the outer Bazel client holds the server
    # lock, so a nested `bazel query` would block indefinitely.  Use a separate
    # output_base (and therefore a separate server) to avoid the deadlock.
    test_tmpdir = env.get("TEST_TMPDIR")
    if test_tmpdir:
        output_base = os.path.join(test_tmpdir, "bazel_query_output_base")
        cmd = ["bazel", f"--output_base={output_base}"] + cmd[1:]

        # `bazel test` strips HOME from the environment. When the `bazel`
        # binary is actually bazelisk, it needs HOME to locate the cached
        # Bazel download. Read it from the password database instead.
        if not env.get("HOME"):
            env["HOME"] = pwd.getpwuid(os.getuid()).pw_dir

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=repo_root,
        env=env,
        check=False,
    )
    target_visibility_targets = [
        line.strip()
        for line in result.stdout.splitlines()
        if line.strip() and line.strip() not in EXCLUDED_PUBLIC_TARGETS
    ]

    load_visibility_targets = _get_public_load_visibility_targets(repo_root)

    all_targets = sorted(set(target_visibility_targets) | set(load_visibility_targets))
    return all_targets
