# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_build_error//lang/cc:defs.bzl", "cc_build_error_test")
load("@rules_build_error//matcher:defs.bzl", "matcher")
load("//quality/unit_testing:unit_testing.bzl", "cc_unit_test")
load("//score/mw:common_features.bzl", "COMPILER_WARNING_FEATURES")

cc_unit_test(
    name = "copyable_atomic_test",
    srcs = ["copyable_atomic_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        "//score/mw/com/impl/util:copyable_atomic",
    ],
)

cc_unit_test(
    name = "arithmetic_utils_test",
    srcs = ["arithmetic_utils_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        "//score/mw/com/impl/util:arithmetic_utils",
        "@score_baselibs//score/language/futurecpp",
    ],
)

cc_unit_test(
    name = "type_erased_storage_test",
    srcs = ["type_erased_storage_test.cpp"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        "//score/mw/com/impl/util:type_erased_storage",
        "@score_baselibs//score/mw/log",
    ],
)

cc_build_error_test(
    name = "arithmetic_utils_addition_build_error_test",
    src = "arithmetic_utils_addition_overflow_build_error_test.cpp",
    compile_stderr = matcher.contains_extended_regex("static assertion failed|static_assert"),
    deps = [
        "//score/mw/com/impl/util:arithmetic_utils",
    ],
)

cc_build_error_test(
    name = "arithmetic_utils_multiplication_build_error_test",
    src = "arithmetic_utils_multiplication_overflow_build_error_test.cpp",
    compile_stderr = matcher.contains_extended_regex("static assertion failed|static_assert"),
    deps = [
        "//score/mw/com/impl/util:arithmetic_utils",
    ],
)
