@startuml
skinparam rectangle {
  BackgroundColor #DFF0D8
  BorderColor black
  RoundCorner 15
}
skinparam {
  DefaultTextAlignment center
}

rectangle "Intra-ECU System Flow Diagram" as lola_flow {
  ' Application Layer
  rectangle "Application Layer" as ApplicationLayer {
    rectangle "Publisher App\n[Data Producer(e.g., Sensor)]"  as Publisher
    rectangle "Subscriber App\n[Data Consumer(e.g., Dashboard)]" as Subscriber
  }

  ' Lola Middleware
  rectangle "Lola Middleware" as LoLa {
    rectangle "\t\tService Discovery\n\n• Register services     \t\t• Find available services\n• Manage connections \t\t• Handle service life cycle" as LoLaServiceDiscovery
  }

  ' Event System
  rectangle "E**NOTE**:vent System" as Event {
    rectangle "Publisher\nSkeleton" as PubSkel
    rectangle "Subscriber\nProxy" as SubProxy
  }

  ' Shared Memory
  rectangle "Shared Memory Manager" as Shared {
    rectangle "Memory\nPool 1" as m1
    rectangle "Memory\nPool 2" as m2
    rectangle "Memory\nPool N" as mN
  }

  ' Operating System
  rectangle "Operating System\n(Linux / QNX Neutrino)" as OS

  ' Relationships
  Publisher -down--> LoLaServiceDiscovery : 1. OfferService()
  Subscriber -down--> LoLaServiceDiscovery : 2. FindService()
  LoLa ----> Event : 3. Service-Match
  PubSkel --right--> SubProxy : 4. Send()
  SubProxy ---left-> PubSkel : 5. Receive()
  Event ---> Shared : 6. Zero-Copy Transfer
  Shared -down-> OS : 7. Direct Memory Access
}

@enduml
