' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../../../../../../../third_party/traceability/doc/sample_library/safety_analysis/fta_metamodel.puml

$TopEvent("Points to wrong data", "Communication.MethodSignatureElementPtrWrongTarget")

$OrGate("Gate1", "TopEvent")
$IntermediateEvent("Shared Memory no longer valid", "Event2", "Gate1")
$BasicEvent("Life-Cycle issues", "Communication.LifeCycleIssues", "Event2")
$IntermediateEvent("Wrong memory location referenced", "Event3", "Gate1")
$OrGate("Gate2", "Event3")
$BasicEvent("References valid memory outside shared-memory", "Event4", "Gate2")
$BasicEvent("References valid memory inside shared-memory", "Event5", "Gate2")
$BasicEvent("References invalid memory", "Event6", "Gate2")

@enduml
