' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include fta_metamodel.puml

$TopEvent("Message lost, incomplete, or corrupted during IPC transmission", "MessagePassing.MessageNotDeliveredCorrectly")

$OrGate("OG1", "MessagePassing.MessageNotDeliveredCorrectly")

$BasicEvent("OS IPC transport failure not detected or handled", "MessagePassing.OsIpcFaultHandling", "OG1")
$BasicEvent("Invalid buffer or size argument passed to SendWaitReply", "MessagePassing.SendBufferArgumentValidation", "OG1")
$BasicEvent("Message exceeds configured max_send_size or max_reply_size", "BE_MessageTooBig", "OG1")
$BasicEvent("Send queue capacity exhausted or configured as zero", "BE_SendQueueExhausted", "OG1")

@enduml
