' *******************************************************************************
' Copyright (c) 2026 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include fta_metamodel.puml

$TopEvent("Server fails to process a received message or produce a required reply", "MessagePassing.ServerMessageHandlingFailure")

$OrGate("OG1", "MessagePassing.ServerMessageHandlingFailure")

$BasicEvent("Message handler does not call Reply within OnMessageSentWithReply", "BE_HandlerNoReply", "OG1")
$BasicEvent("Message handler returns an error that is not propagated to the client", "BE_HandlerErrorUnpropagated", "OG1")
$BasicEvent("Message callback or connection handler not registered at StartListening", "BE_HandlerNotRegistered", "OG1")

@enduml
