# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "only_partially_offered_fta",
    srcs = [
        "only_partially_offered_fta.puml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "service_offered_under_wrong_id_fta",
    srcs = [
        "service_offered_under_wrong_id_fta.puml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "skeleton_not_offered_without_initial_field_value_fta",
    srcs = [
        "skeleton_not_offered_without_initial_fieled_value_fta.puml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "skeleton_offered_wrong_binding_fta",
    srcs = [
        "skeleton_offered_wrong_binding_fta.puml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "skeleton_not_offered_fta",
    srcs = [
        "skeleton_not_offered_fta.puml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "offers_already_offered_service_fta",
    srcs = [
        "offers_already_offered_service_fta.puml",
    ],
    visibility = ["//visibility:public"],
)
