' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../fta_metamodel.puml

$TopEvent("Offers already offered service", "TopEvent")

$OrGate("Gate1", "TopEvent")
$BasicEvent("Service was offered by another process", "Event3", "Gate1")
$BasicEvent("Service was already offered by our process", "Event2", "Gate1")
$BasicEvent("Service was already offered by previous died process", "Event1", "Gate1")

@enduml
