' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../fta_metamodel.puml

$TopEvent("Only partially offered", "Communication.ServiceOnlyPartiallyOffered")

$OrGate("Gate1", "TopEvent")
$IntermediateEvent("Not all quality levels are served", "Event1", "Gate1")
$TransferIn("Transfer1", "Event1")
$IntermediateEvent("Not all events are offered", "Event2", "Gate1")
$OrGate("Gate2", "Event2")
$BasicEvent("Not all events are populated", "Communication.NotAllEventsArePopulated", "Gate2")
$IntermediateEvent("Config is wrong", "Event3", "Gate2")
$TransferIn("Transfer2", "Event3")

@enduml
