/********************************************************************************
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

//! Integration tests for primitive types.
//! Each type has its own interface (generated by `interface!`) so every test
//! creates a producer/consumer pair using only the event it needs.

#[cfg(test)]
mod primitive_type_tests {
    use crate::generate_test;
    use crate::test_types::{
        BoolData, BoolInterface, F32Data, F32Interface, F64Data, F64Interface, I16Data,
        I16Interface, I32Data, I32Interface, I64Data, I64Interface, I8Data, I8Interface, U16Data,
        U16Interface, U32Data, U32Interface, U64Data, U64Interface, U8Data, U8Interface,
    };

    generate_test!(
        test = test_u8_send_receive,
        interface = U8Interface,
        event = u8_event,
        path = "/PrimitiveTest/U8",
        data = U8Data { value: 255_u8 },
        assert = |a: &U8Data, b: &U8Data| assert_eq!(a.value, b.value),
    );

    generate_test!(
        test = test_u16_send_receive,
        interface = U16Interface,
        event = u16_event,
        path = "/PrimitiveTest/U16",
        data = U16Data { value: u16::MAX },
        assert = |a: &U16Data, b: &U16Data| assert_eq!(a.value, b.value),
    );

    generate_test!(
        test = test_u32_send_receive,
        interface = U32Interface,
        event = u32_event,
        path = "/PrimitiveTest/U32",
        data = U32Data { value: u32::MAX },
        assert = |a: &U32Data, b: &U32Data| assert_eq!(a.value, b.value),
    );

    generate_test!(
        test = test_u64_send_receive,
        interface = U64Interface,
        event = u64_event,
        path = "/PrimitiveTest/U64",
        data = U64Data { value: u64::MAX },
        assert = |a: &U64Data, b: &U64Data| assert_eq!(a.value, b.value),
    );

    generate_test!(
        test = test_i8_send_receive,
        interface = I8Interface,
        event = i8_event,
        path = "/PrimitiveTest/I8",
        data = I8Data { value: i8::MIN },
        assert = |a: &I8Data, b: &I8Data| assert_eq!(a.value, b.value),
    );

    generate_test!(
        test = test_i16_send_receive,
        interface = I16Interface,
        event = i16_event,
        path = "/PrimitiveTest/I16",
        data = I16Data { value: i16::MIN },
        assert = |a: &I16Data, b: &I16Data| assert_eq!(a.value, b.value),
    );

    generate_test!(
        test = test_i32_send_receive,
        interface = I32Interface,
        event = i32_event,
        path = "/PrimitiveTest/I32",
        data = I32Data { value: i32::MIN },
        assert = |a: &I32Data, b: &I32Data| assert_eq!(a.value, b.value),
    );

    generate_test!(
        test = test_i64_send_receive,
        interface = I64Interface,
        event = i64_event,
        path = "/PrimitiveTest/I64",
        data = I64Data { value: i64::MIN },
        assert = |a: &I64Data, b: &I64Data| assert_eq!(a.value, b.value),
    );

    generate_test!(
        test = test_f32_send_receive,
        interface = F32Interface,
        event = f32_event,
        path = "/PrimitiveTest/F32",
        data = F32Data { value: 3.14159_f32 },
        assert = |a: &F32Data, b: &F32Data| assert!((a.value - b.value).abs() < 1e-5_f32),
    );

    generate_test!(
        test = test_f64_send_receive,
        interface = F64Interface,
        event = f64_event,
        path = "/PrimitiveTest/F64",
        data = F64Data {
            value: 3.141_592_653_589_793_f64
        },
        assert = |a: &F64Data, b: &F64Data| assert!((a.value - b.value).abs() < 1e-7_f64),
    );

    generate_test!(
        test = test_bool_send_receive,
        interface = BoolInterface,
        event = bool_event,
        path = "/PrimitiveTest/Bool",
        data = BoolData { value: true },
        assert = |a: &BoolData, b: &BoolData| assert_eq!(a.value, b.value),
    );
}
