/********************************************************************************
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

//! Integration tests for user-defined types.
//! Each type has its own interface (generated by `interface!`) so every test
//! creates a producer/consumer pair using only the event it needs.

#[cfg(test)]
mod user_defined_type_tests {
    use crate::test_types::{
        ComplexStruct, ComplexStructInterface, NestedStruct, NestedStructInterface, Point, Point3D,
        Point3DInterface, PointInterface, SensorData, SensorDataInterface, SimpleStruct,
        SimpleStructInterface, VehicleState, VehicleStateInterface,
    };
    use crate::generate_test;

    generate_test!(
        test = test_simple_struct_send_receive,
        interface = SimpleStructInterface,
        event = simple_event,
        path = "/UserDefinedTest/SimpleStruct",
        data = SimpleStruct { id: 42 },
        assert = |r: &SimpleStruct, e: &SimpleStruct| assert_eq!(r.id, e.id),
    );

    generate_test!(
        test = test_complex_struct_send_receive,
        interface = ComplexStructInterface,
        event = complex_event,
        path = "/UserDefinedTest/ComplexStruct",
        data = ComplexStruct {
            count: 42,
            temperature: 25.5,
            is_active: 1,
            timestamp: 1234567890
        },
        assert = |r: &ComplexStruct, e: &ComplexStruct| {
            assert_eq!(r.count, e.count);
            assert!((r.temperature - e.temperature).abs() < 0.01);
            assert_eq!(r.is_active, e.is_active);
            assert_eq!(r.timestamp, e.timestamp);
        },
    );

    generate_test!(
        test = test_nested_struct_send_receive,
        interface = NestedStructInterface,
        event = nested_event,
        path = "/UserDefinedTest/NestedStruct",
        data = NestedStruct {
            id: 1,
            simple: SimpleStruct { id: 123 },
            value: 99.9
        },
        assert = |r: &NestedStruct, e: &NestedStruct| {
            assert_eq!(r.id, e.id);
            assert_eq!(r.simple.id, e.simple.id);
            assert!((r.value - e.value).abs() < 0.01);
        },
    );

    generate_test!(
        test = test_point_2d_send_receive,
        interface = PointInterface,
        event = point_event,
        path = "/UserDefinedTest/Point",
        data = Point { x: 1.5, y: 2.5 },
        assert = |r: &Point, e: &Point| {
            assert!((r.x - e.x).abs() < 0.001);
            assert!((r.y - e.y).abs() < 0.001);
        },
    );

    generate_test!(
        test = test_point_3d_send_receive,
        interface = Point3DInterface,
        event = point3d_event,
        path = "/UserDefinedTest/Point3D",
        data = Point3D {
            x: 1.0,
            y: 2.0,
            z: 3.0
        },
        assert = |r: &Point3D, e: &Point3D| {
            assert!((r.x - e.x).abs() < 0.001);
            assert!((r.y - e.y).abs() < 0.001);
            assert!((r.z - e.z).abs() < 0.001);
        },
    );

    generate_test!(
        test = test_sensor_data_send_receive,
        interface = SensorDataInterface,
        event = sensor_event,
        path = "/UserDefinedTest/SensorData",
        data = SensorData {
            sensor_id: 1,
            temperature: 22.5,
            humidity: 45.0,
            pressure: 1013.25
        },
        assert = |r: &SensorData, e: &SensorData| {
            assert_eq!(r.sensor_id, e.sensor_id);
            assert!((r.temperature - e.temperature).abs() < 0.01);
            assert!((r.humidity - e.humidity).abs() < 0.01);
            assert!((r.pressure - e.pressure).abs() < 0.01);
        },
    );

    generate_test!(
        test = test_vehicle_state_send_receive,
        interface = VehicleStateInterface,
        event = vehicle_event,
        path = "/UserDefinedTest/VehicleState",
        data = VehicleState {
            speed: 60.0,
            rpm: 3000,
            fuel_level: 75.0,
            is_running: 1,
            mileage: 50000
        },
        assert = |r: &VehicleState, e: &VehicleState| {
            assert!((r.speed - e.speed).abs() < 0.1);
            assert_eq!(r.rpm, e.rpm);
            assert!((r.fuel_level - e.fuel_level).abs() < 0.1);
            assert_eq!(r.is_running, e.is_running);
            assert_eq!(r.mileage, e.mileage);
        },
    );
}
