# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "changes_user_data_fta",
    srcs = [
        "changes_user_data_fta.puml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "does_not_free_resources_after_usage_fta",
    srcs = [
        "does_not_free_resources_after_usage_fta.puml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "only_partially_notifies_user_fta",
    srcs = [
        "only_partially_notifies_user_fta.puml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sends_to_wrong_consumer_fta",
    srcs = [
        "sends_to_wrong_consumer_fta.puml",
    ],
    visibility = ["//visibility:public"],
)
