' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include fta_metamodel.puml

$TopEvent("Wrong input arguments used", "Communication.WrongMethodInArgsUsed")

$OrGate("Gate1", "Communication.WrongMethodInArgsUsed")
$IntermediateEvent("Callee used wrong InArgs", "Event1", "Gate1")
$IntermediateEvent("Callee used corrupted InArgs", "Event2", "Gate1")
$OrGate("Gate2", "Event1")
$OrGate("Gate3", "Event2")
$BasicEvent("Callee used InArgs from wrong location", "Communication.CalleeUsedInArgsFromWrongLocation", "Gate2")
$BasicEvent("Callee used InArgs before being provided", "Communication.CalleeUsedInArgsBeforeBeingProvided", "Gate2")

$BasicEvent("Callee used InArgs in wrong layout", "Communication.CalleeUsedInArgsInWrongLayout", "Gate3")
$BasicEvent("Callee used InArgs while concurrently updated", "Communication.CalleeUsedInArgsWhileConcurrentlyUpdated", "Gate3")
$BasicEvent("InArgs corrupted by 3d party", "Communication.InArgsCorruptedBy3rdParty", "Gate3")

@enduml
