# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("@score_baselibs//score/language/safecpp:toolchain_features.bzl", "COMPILER_WARNING_FEATURES")
load("//score/mw/com/test:pkg_application.bzl", "pkg_application")

cc_library(
    name = "service_interface",
    srcs = ["hello_world_service.cpp"],
    hdrs = ["hello_world_service.h"],
    features = COMPILER_WARNING_FEATURES,
    deps = [
        "//score/mw/com",
    ],
)

cc_binary(
    name = "provider_app",
    srcs = [
        "provider/provider.cpp",
        "provider/provider.h",
    ],
    data = ["provider/mw_com_config.json"],
    features = COMPILER_WARNING_FEATURES + [
        "aborts_upon_exception",
    ],
    deps = [
        ":service_interface",
        "//score/mw/com",
    ],
)

cc_binary(
    name = "consumer_app",
    srcs = [
        "consumer/consumer.cpp",
        "consumer/consumer.h",
    ],
    features = COMPILER_WARNING_FEATURES + [
        "aborts_upon_exception",
    ],
    deps = [
        ":service_interface",
        "//score/mw/com",
    ],
)

pkg_application(
    name = "provider-pkg",
    app_name = "HelloWorldServer",
    bin = [":provider_app"],
    etc = [
        "provider/logging.json",
        "provider/mw_com_config.json",
    ],
    visibility = [
        "//score/mw/com/doc:__subpackages__",
    ],
)

pkg_tar(
    name = "provider-tar",
    srcs = [":provider-pkg"],
    visibility = [
        "//score/mw/com/doc:__subpackages__",
    ],
)

# Two consumer application packages. They share the very same 'consumer' binary and only differ in the bundled
# mw_com_config.json (specifically its applicationID), so that both instances can run side by side.
pkg_application(
    name = "consumer1-pkg",
    app_name = "HelloWorldClient1",
    bin = [":consumer_app"],
    etc = [
        "consumer/logging.json",
        "consumer/client_1/mw_com_config.json",
    ],
    visibility = [
        "//score/mw/com/doc:__subpackages__",
    ],
)

pkg_tar(
    name = "consumer1-tar",
    srcs = [":consumer1-pkg"],
    visibility = [
        "//score/mw/com/doc:__subpackages__",
    ],
)

pkg_application(
    name = "consumer2-pkg",
    app_name = "HelloWorldClient2",
    bin = [":consumer_app"],
    etc = [
        "consumer/logging.json",
        "consumer/client_2/mw_com_config.json",
    ],
    visibility = [
        "//score/mw/com/doc:__subpackages__",
    ],
)

pkg_tar(
    name = "consumer2-tar",
    srcs = [":consumer2-pkg"],
    visibility = [
        "//score/mw/com/doc:__subpackages__",
    ],
)

filegroup(
    name = "chapter_6",
    srcs = [
        ":consumer1-tar",
        ":consumer2-tar",
        ":provider-tar",
    ],
    visibility = ["//score/mw/com/doc:__subpackages__"],
)

filegroup(
    name = "doc_files",
    srcs = glob([
        "**/*.rst",
        "**/*.cpp",
        "**/*.h",
        "**/*.json",
    ]),
    visibility = ["//score/mw/com/doc/tutorial:__pkg__"],
)
