# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "subscribe_to_wrong_event_fta",
    srcs = [
        "subscribe_to_wrong_event_fta.puml",
        "//score/mw/com/requirements/safety_analysis/failure_modes:fta_metamodel",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "subscribe_with_wrong_max_sample_count_fta",
    srcs = [
        "subscribe_with_wrong_max_sample_count_fta.puml",
        "//score/mw/com/requirements/safety_analysis/failure_modes:fta_metamodel",
    ],
    visibility = ["//visibility:public"],
)
