# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Other options:
# "@score_baselibs//score/analysis/tracing/generic_trace_library/stub_implementation"
# "@score_baselibs//score/analysis/tracing/generic_trace_library/stub_implementation"
label_flag(
    name = "tracing_library",
    build_setting_default = "@score_baselibs//score/analysis/tracing/generic_trace_library",
    visibility = [
        "//score/mw/com/impl/tracing:__subpackages__",
    ],
)
