load(
    "@score_tooling//bazel/rules/rules_score:sphinx_toolchain.bzl",
    "sphinx_toolchain",
)
load(
    "@score_tooling//cpp/libclang:libclang_toolchain.bzl",
    "libclang_toolchain",
)

# ============================================================================
# libclang toolchain for the C++ parser used by score rules
# ============================================================================
libclang_toolchain(
    name = "score_communication_libclang",
    cxx_builtin_include = "@llvm_toolchain_llvm//:cxx_builtin_include",
    extra_config_site = "@llvm_toolchain_llvm//:extra_config_site",
    libclang = "@llvm_toolchain_llvm//:lib/libclang.so",
)

toolchain(
    name = "score_communication_libclang_toolchain",
    toolchain = ":score_communication_libclang",
    toolchain_type = "@score_tooling//cpp/libclang:libclang_toolchain_type",
    visibility = ["//:__subpackages__"],
)

py_binary(
    name = "sphinx_build",
    srcs = ["@score_tooling//bazel/rules/rules_score:src/sphinx_wrapper.py"],
    data = [
        "@score_tooling//plantuml:fta_metamodel",
        "@score_tooling//third_party/docs_runtime:dot",
        "@score_tooling//third_party/plantuml",
    ],
    exec_compatible_with = ["@platforms//os:linux"],
    main = "@score_tooling//bazel/rules/rules_score:src/sphinx_wrapper.py",
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//:__subpackages__"],
    deps = [
        "@rules_python//python/runfiles",
        "@score_communication_pip//breathe:pkg",
        "@score_communication_pip//myst_parser:pkg",
        "@score_communication_pip//pydata_sphinx_theme:pkg",
        "@score_communication_pip//sphinx:pkg",
        "@score_communication_pip//sphinx_design:pkg",
        "@score_communication_pip//sphinx_needs:pkg",
        "@score_communication_pip//sphinx_rtd_theme:pkg",
        "@score_communication_pip//sphinxcontrib_plantuml:pkg",
        "@score_tooling//bazel/rules/rules_score:bazel_sphinx_needs",
        "@score_tooling//bazel/rules/rules_score:sphinx_module_ext",
        "@score_tooling//plantuml/sphinx/clickable_plantuml",
        "@trlc//tools/sphinx/extensions/trlc",
    ],
)

sphinx_toolchain(
    name = "score_sphinx_toolchain",
    conf_template = "template/conf.template.py",
    sphinx = ":sphinx_build",
    target_compatible_with = ["@platforms//os:linux"],
)

toolchain(
    name = "sphinx_toolchain",
    exec_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    target_compatible_with = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
    ],
    toolchain = ":score_sphinx_toolchain",
    toolchain_type = "@score_tooling//bazel/rules/rules_score:toolchain_type",
    visibility = ["//:__subpackages__"],
)
