# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

filegroup(
    name = "callback_invoked_with_wrong_data_fta",
    srcs = [
        "callback_invoked_with_wrong_data_fta.puml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "callback_not_invoked_despite_samples_available_fta",
    srcs = [
        "callback_not_invoked_despite_samples_available_fta.puml",
    ],
    visibility = ["//visibility:public"],
)
