' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../fta_metamodel.puml

$TopEvent("Allocate in Wrong Memory", "TopEvent")

$OrGate("Gate1", "TopEvent")
$IntermediateEvent("Allocate in Heap", "Event1", "Gate1")
$OrGate("Gate2", "Event1")
$IntermediateEvent("Usage of wrong memory ressource", "Event11", "Gate2")
$OrGate("Gate4", "Event11")
$IntermediateEvent("getMemoryResourceProxy returns wrong ressource", "Event14", "Gate4")
$OrGate("Gate5", "Event14")
$IntermediateEvent("Proxy dispatch over memory resource registry returns wrong ressource", "Event20", "Gate5")
$IntermediateEvent("Registry broken", "Event22", "Event20")
$BasicEvent("Proxy ID overwritten", "Event23", "Event22")
$BasicEvent("Shared Memory resource returns wrong proxy", "Event21", "Gate5")
$BasicEvent("SharedMemoryFactory returns wrong memory ressource", "Event17", "Gate4")
$IntermediateEvent("Usage of no memory ressource", "Event10", "Gate2")
$OrGate("Gate3", "Event10")
$BasicEvent("Shared Memory ressource not forwarded", "Event16", "Gate3")
$BasicEvent("User Fehler", "Event15", "Gate3")
$IntermediateEvent("Usage of Wrong Allocator", "Event9", "Gate2")
note left of Event9
  This includes usage
  of allocator unaware
  types
end note
$OrGate("Gate6", "Event9")
$BasicEvent("Middleware provided type is wrong", "Event19", "Gate6")
$BasicEvent("User provided type is wrong", "Event18", "Gate6")
$IntermediateEvent("Allocate in other SHM", "Event2", "Gate1")
$OrGate("Gate7", "Event2")
$BasicEvent("Shared memory Resource opens wrong shared memory segment", "Event6", "Gate7")
$BasicEvent("Forwarded the wrong shared memory segment from the beginning", "Event5", "Gate7")
$IntermediateEvent("Allocator dispatches to wrong memory ressource", "Event4", "Gate7")
$OrGate("Gate8", "Event4")
$BasicEvent("Offset PTR corruption", "Event13", "Gate8")
$BasicEvent("Proxy ID overwritten", "Event12", "Gate8")
$IntermediateEvent("Allocate on Stack", "Event3", "Gate1")
$OrGate("Gate9", "Event3")
$BasicEvent("Broken allocator", "Event7", "Gate9")
$BasicEvent("Data-Type itself is allocated on stack", "Event8", "Gate9")

@enduml
