' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../fta_metamodel.puml

$TopEvent("To few memory allocated", "TopEvent")

$OrGate("Gate1", "TopEvent")
$IntermediateEvent("Wrong slot-type choosen", "Event2", "Gate1")
$BasicEvent("Mapping from actual EventID to Event-Type incorrect", "Event4", "Event2")
$IntermediateEvent("A slot cannot be allocated", "Event3", "Gate1")
$OrGate("Gate2", "Event3")
$IntermediateEvent("To few slots allocated", "Event12", "Gate2")
$OrGate("Gate4", "Event12")
$BasicEvent("Literaly wrong number of slots reserved", "Event14", "Gate4")
$IntermediateEvent("Configuration issue", "Event17", "Gate4")
$TransferIn("Transfer1", "Event17")
$IntermediateEvent("Proxy violates contract", "Event11", "Gate2")
$OrGate("Gate6", "Event11")
$BasicEvent("Holds more SamplePtr than announced", "Event13", "Gate6")
$BasicEvent("Holds more SamplePtr than configured", "Event15", "Gate6")
$IntermediateEvent("Slot allocation logic broken", "Event8", "Gate2")
$OrGate("Gate3", "Event8")
$BasicEvent("Consumer uses an older slot, than he already has blocked in the previous access", "Event19", "Gate3")
$BasicEvent("Retry-logic not bullet proof", "Event18", "Gate3")
$BasicEvent("Issue in Lock-free Sychronization", "Event16", "Gate3")
$BasicEvent("More than one SampleAllocateePtr in parallel", "Event10", "Gate2")
$IntermediateEvent("Dynamic Memory for containers in slots cannot be allocated", "Event1", "Gate1")
$OrGate("Gate5", "Event1")
$BasicEvent("Allocate claims to few memory", "Event7", "Gate5")
$IntermediateEvent("Configuration broken", "Event9", "Gate5")
$TransferIn("Transfer2", "Event9")
$BasicEvent("Necessary size calculation retreives wrong value", "Event6", "Gate5")
$BasicEvent("Shared memory truncation fails", "Event5", "Gate5")

@enduml
