' Copyright (c) 2025 Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' <https://www.apache.org/licenses/LICENSE-2.0>
'
' SPDX-License-Identifier: Apache-2.0

@startuml
'https://plantuml.com/component-diagram
package "com-api" {
    [Com API]
}

package "com-api-runtime" {

    [Com API] <-- [RuntimeImpl]
    [RuntimeImpl] --> [SampleConsumerBuilder]
    [RuntimeImpl] --> [SampleProducerBuilder]
}

package "com-api" {
    [Com API]
}

package "com-api-gen" #Yellow {
    [Tire]
    [Exhaust]
    [VehicleInterface] --> [Tire]
    [VehicleInterface] --> [Exhaust]
    [Provider<VehicleInterface>] --> [VehicleInterface]
    [Consumer<VehicleInterface>] --> [VehicleInterface]
    [Provider<VehicleInterface>] --> [Com API]
    [Consumer<VehicleInterface>] --> [Com API]
    [SampleConsumerBuilder] --> [Provider<VehicleInterface>]
    [SampleProducerBuilder] --> [Consumer<VehicleInterface>]

    note top of [Provider<VehicleInterface>]
        Code that implements providing VehicleInterface
        in terms of RuntimeImpl.
    end note

    note top of [Consumer<VehicleInterface>]
        Code that implements using VehicleInterface
        in terms of RuntimeImpl.
    end note
}

note top of "com-api-gen"
        This crate knows all supported interfaces
        and provides instances for them that are
        implemented in terms of
        com-api-runtime::SampleProviderBuilder
        and com-api-runtime::SampleConsumerBuilder
end note

package "com-api-sample" {
    [Factory]
    [Business Logic] --> [VehicleInterface]
    [Business Logic] --> [Exhaust]
    [Business Logic] --> [Tire]
    [Factory] --> [RuntimeImpl]
    [Factory] --> [Com API]
    [Factory] .> [Business Logic] : builds
}

package "Package" #Yellow
note bottom of "Package"
    Yellow = generated
end note

@enduml
