# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@score_tooling//bazel/rules/rules_score:rules_score.bzl", "unit_design")

unit_design(
    name = "client_connection_unit_design",
    visibility = ["//score/message_passing:__pkg__"],
)

unit_design(
    name = "unix_domain_unit_design",
    visibility = ["//score/message_passing:__pkg__"],
)

unit_design(
    name = "qnx_dispatch_unit_design",
    visibility = ["//score/message_passing:__pkg__"],
)

unit_design(
    name = "server_connection_unit_design",
    visibility = ["//score/message_passing:__pkg__"],
)
