' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include ../../fta_metamodel.puml

$TopEvent("Service is found, but does not exist", "TopEvent")

$OrGate("Gate1", "TopEvent")
$BasicEvent("Service was offered, but not unliked on stop offer", "Event2", "Gate1")
$BasicEvent("Shared Memory is opened eventhough file does not exist", "Event1", "Gate1")
$IntermediateEvent("Shared Memory Object exists but not accessable", "Event3", "Gate1")
$OrGate("Gate2", "Event3")
$BasicEvent("Wrong Provider", "Event7", "Gate2")
$BasicEvent("Wrong Name", "Event6", "Gate2")
$BasicEvent("Wrong ACL", "Event5", "Gate2")
$BasicEvent("Shared Memory Object does not exist", "Event4", "Gate1")

@enduml
