' *******************************************************************************
' Copyright (c) {year} Contributors to the Eclipse Foundation
'
' See the NOTICE file(s) distributed with this work for additional
' information regarding copyright ownership.
'
' This program and the accompanying materials are made available under the
' terms of the Apache License Version 2.0 which is available at
' https://www.apache.org/licenses/LICENSE-2.0
'
' SPDX-License-Identifier: Apache-2.0
' *******************************************************************************

@startuml

!include fta_metamodel.puml

$TopEvent("In-Memory configuration wrong", "Communication.InMemoryConfigurationWrong")

$OrGate("Gate1", "TopEvent")
$BasicEvent("User provided wrong configuration", "Communication.UserProvidedWrongConfiguration", "Gate1")
$IntermediateEvent("JSON-Tree corrupt", "Event2", "Gate1")
$OrGate("Gate2", "Event2")
$BasicEvent("File corrupted", "Communication.FileCorrupted", "Gate2")
$BasicEvent("JSON Parser broken", "Communication.JsonParserBroken", "Gate2")
$IntermediateEvent("Configuration gets corrupted reading the JSON-Tree", "Event3", "Gate1")
$OrGate("Gate3", "Event3")
$BasicEvent("Manipulate read data", "Communication.ManipulateReadData", "Gate3")
$BasicEvent("Omit reading of relevant elements", "Communication.OmitReadingOfRelevantElements", "Gate3")

@enduml
